config/routes.rb
Rails.application.routes.draw do
 
  get '/', to: 'application#index', as: 'root'



  resources :pets
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, :only => [:index, :show, :update] 

  devise_scope :user do
    get '/signin', to: 'users/sessions#new'
    get '/signout', to: 'users/sessions#destroy'
    post '/interested', to: 'pets#interested'
    get '/users/admindelete/:id', to: 'users#destroy'
    get '/users/adminupdate/:id', to: 'users#edit'
    
  end
   
  
 
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :interested
  has_many :pets, through: :interested 
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :omniauthable, :omniauth_providers => [:google_oauth2]
   
  validates_uniqueness_of :email, :case_sensitive => false
  validates_presence_of :email, :on=>:create
  validates_format_of :email, :with  => Devise.email_regexp
  validates_presence_of :password, :on=>:create
  validates_confirmation_of :password, :on=>:create
  enum role: ["admin", "user"]

  scope :pets_interested, -> {joins(:interested).group('users.name')}
  scope :interested_cats, -> {joins(:interested).where('pets.species = cat').group('users.name')}
  scope :interested_dogs, -> {joins(:interested).where('pets.species = dog').group('users.name')}

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(:email => data["email"]).first
  
    unless user
      password = Devise.friendly_token[0,20]
      user = User.create(name: data["name"], email: data["email"],
        password: password, password_confirmation: password
      )
    end
    user
  end

  def joindate
    self.created_at.strftime("%B %d, %Y")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    respond_to :html, :json

    def index
        if user_signed_in?


            @interested_user = Interested.where(:user_id => current_user.id)
         #  raise params.inspect
        #     @pets = Pet.all
        #     @pet_ids = []
        #     
       
        #     @interested_user = current_user.interested.all
        
            @interest_pets = @interested_user.map do |eachuser| eachuser.pet_id
            end
            @pet_objects = []
            @interest_pets.each do |eachpet|
                if Pet.any?{|h| h[:id] == eachpet}
                        @pet_objects << Pet.find(eachpet)
                end
            end
            #raise params.inspect
        end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Shelter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="topnav">
      <a class="active" href="<%= root_url %>"/>Home</a>
      <% if current_user%>
        <% if current_user.role == "admin" %>
          <%= link_to "Admin", users_path %>
        <% end %>
      <%end%>

      <%= link_to 'Adoptable!', pets_path %> 


      <% if user_signed_in? %>
        <%= link_to 'Edit profile', edit_user_registration_path %> 
        <%= link_to 'Sign Out', signout_path, method: :delete %>  
        <% else %>
        <%= link_to "Sign up",  new_user_registration_path  %> 
        <%= link_to "Login", signin_path %>
     <%end%>

    </div>
      
        <div class= "topnav-p">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>
        <%end%></div>
 
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    


    <!-- content -->
    <div class="container"  role="main">

        <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <section class="flash flash__<%= key %>"><%= value.html_safe %></section>
      <% end -%>
    <% end %>
      <%= yield %>
  
    
 
    </div>
  </body>
</html>